filename_regex: .*\.png
filename_regex_case_sensitive: false
polling_frequency_ms: 1000
use_polling: true
watch_dirpath: ./
window_title_regex: ".*File Explorer.*"
window_title_regex_case_sensitive: false
window_watcher_tolerance: 0.05
