dir_watcher:
  filename_regex: .*\.(jpg|png)
  interval: 1.0
  watch_dirpath: ./
image_previewer:
  interval: 1.0
window_watcher:
  interval: 5.0
  title_regex: .*File Explorer.*
  tolerance: 0.05
